# Generated by Django 4.2 on 2023-05-31 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0006_product_description_en_us_product_description_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Кол-во должно быть >= 0')], verbose_name='Количество'),
        ),
    ]
