# Generated by Django 4.2 on 2023-06-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0008_alter_category_name_alter_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
