# Generated by Django 4.2 on 2023-06-01 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0009_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name', max_length=100, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Category name', max_length=100, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Category name', max_length=100, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Choose a category name', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='simpleapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Describe the product', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en_us',
            field=models.TextField(help_text='Describe the product', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(help_text='Describe the product', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter a name of the product', max_length=50, unique=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(help_text='Enter a name of the product', max_length=50, null=True, unique=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(help_text='Enter a name of the product', max_length=50, null=True, unique=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Цена должна быть >= 0.0', validators=[django.core.validators.MinValueValidator(0.0, 'Price should be >= 0.0')], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(help_text='Количество должно быть >= 0', validators=[django.core.validators.MinValueValidator(0, 'Quantity should be >= 0')], verbose_name='Quantity'),
        ),
    ]
